version: '3'
services:
  mycalendar:
    environment:
      FLASK_ENV: development
      FLASK_APP: mycalendar.server.factory
      DB_URL: postgres://db_user:db_pw@db/calendar_db
      TEST_DB_URL: postgres://test_db_user:test_db_pw@db/calendar_test_db
    build: ./
    image: mycalendar
    working_dir: /usr/src/app
    volumes: 
      - ./:/usr/src/app/
    command: poetry run flask run --host=0.0.0.0 --port=80
    ports:
      - "80:80"
    networks:
      - szoftarch
    depends_on:
      - db
  
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: calendar_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pw
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./postgres:/docker-entrypoint-initdb.d/
    networks:
      - szoftarch

networks:
  szoftarch:
    external: true

volumes:
  database-data:
