"""Make event start and end unique together

Revision ID: 33101e092581
Revises: 93ff64d86b8a
Create Date: 2020-10-23 19:09:19.535468

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "33101e092581"
down_revision = "93ff64d86b8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_start_end", "events", ["start", "end"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_start_end", "events", type_="unique")
    # ### end Alembic commands ###
