"""Add guest_name column to events

Revision ID: 46aafa5d6967
Revises: b3b83bb41fd8
Create Date: 2020-11-07 18:13:45.102685

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "46aafa5d6967"
down_revision = "b3b83bb41fd8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("guest_name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "guest_name")
    # ### end Alembic commands ###
