"""Add year column to weeks

Revision ID: 7d088b510ba0
Revises: cd11670f1c80
Create Date: 2020-10-23 16:16:22.944686

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7d088b510ba0"
down_revision = "cd11670f1c80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("weeks", sa.Column("year", sa.Integer(), nullable=False))
    op.create_unique_constraint(
        "unique_year_week", "weeks", ["year", "week_num"]
    )
    op.drop_constraint("weeks_week_num_key", "weeks", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("weeks_week_num_key", "weeks", ["week_num"])
    op.drop_constraint("unique_year_week", "weeks", type_="unique")
    op.drop_column("weeks", "year")
    # ### end Alembic commands ###
