"""Connect events to users

Revision ID: 93ff64d86b8a
Revises: 7d088b510ba0
Create Date: 2020-10-23 17:14:16.379442

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "93ff64d86b8a"
down_revision = "7d088b510ba0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "events_user_id_fkey", "events", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("events_user_id_fkey", "events", type_="foreignkey")
    op.drop_column("events", "user_id")
    # ### end Alembic commands ###
