"""Make event dates and user_id unique

Revision ID: b3b83bb41fd8
Revises: 33101e092581
Create Date: 2020-10-24 09:25:25.392579

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3b83bb41fd8"
down_revision = "33101e092581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_start_end_user_id", "events", ["start", "end", "user_id"]
    )
    op.drop_constraint("unique_start_end", "events", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_start_end", "events", ["start", "end"])
    op.drop_constraint("unique_start_end_user_id", "events", type_="unique")
    # ### end Alembic commands ###
