# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          apt-get -y update && apt-get -y upgrade
          apk-get -y install curl gcc musl-dev
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          /root/.poetry/bin/poetry install
          /root/.poetry/bin/poetry run isort --recursive --check-only vmagent tests
          /root/.poetry/bin/poetry run black --check vmagent tests
          /root/.poetry/bin/poetry run nose2 -v
